name: CI
on: push

jobs:
  build-debug:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - run: git checkout HEAD^
    - name: Build Generic Debuggable Linux Binary
      run: ./build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Debug Artifact
        path: bin/fixmydl

  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Generic Releasable Linux Binary
      run: ./buildRelease.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Release Artifact
        path: bin/fixmydl

  build-docker-debug:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Build Debuggable Installers
      run: |
        ./buildDocker.sh
        ./buildArtifacts.sh build
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Debuggable Installers
        path: artifacts/
      
  build-docker-release:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Build Releasable Installers
      run: |
        ./buildDockerRelease.sh
        ./buildArtifacts.sh buildRelease
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Releasable Installers
        path: artifacts/
